### ISSUE TITLE
Add Animation when a FAQ section in opened [GSSOC'23]

### ISSUE THREAD

**Issue by kartikayasija** [aniketsinha2002/DataScienceWebsite.github.io#15]
When a FAQ section is clicked, it should open with an animation.
<img width="793" alt="image" src="https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/115306535/15bf2661-2aae-46da-bb76-71fbc6e0f209">

I want to work on this, Please assign me this issue.

**Comment by Nishannaik** [comment]
I want to work on this, Please assign me this issue.

**Comment by Nishannaik** [comment]
@kartikayasija Interested to explore and contribute under GSOC 23.

**Comment by kartikayasija** [comment]
> @kartikayasija Interested to explore and contribute under GSOC 23.

Hey Nishannaik, I am not the mentor of this Project. I am also a contributor.

**Comment by aniketsinha2002** [comment]
@Nishannaik  Please note that I can only assign issues on a first-come, first-serve basis. If you find any issues that haven't been opened or assigned to anyone, please open an issue and start working on it.

Also, I will also be opening up issues that need to be fixed by someone within a day or two. You can contribute to those as well. Stay active!
